### PR TITLE
Armor And Glint Updates

### PR DESCRIPTION
**Pull request by zanduh**

### CODE REVIEW

**Review by 0ffz — COMMENTED** [review]
How come the layer 1 for all the armor is being deleted? If this changes how armor looks, could I see a screenshot of it?

**Comment by zanduh** [comment]
The change to each armor set is a fix to the helmet which moves the rim up a pixel. When I was active a few months back that was the main complaint. I set a poll after that which we looked at the current color scheme vs muted colors. The current colors won the poll. Below is a comparison of the enchanted diamond armor with the old and new glint and helmet.

Old 



New

**Comment by 0ffz** [comment]
Ok these look great ingame, only thing is the glint is way too fast ingame. I don't know if there's really any point in changing it? Perhaps just use the vanilla one and make it a little bit more transparent since that's what seems to bother people the most.

**Comment by 0ffz** [comment]
I'll be reverting the glint changes in here tomorrow so we can at least merge in the new armor finally. Glint changes can come in another PR once we figure that out.

**Review by 0ffz — APPROVED** [review]

**Pull request merged**
