### PR TITLE
More emotes

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Comment by Boy0000** [comment]
ehhhh not sure about those 2 first commits there. Made a new branch?

**Comment by 0ffz** [comment]
I've been thinking, since we're probably going to want items out of all the whistles/bells, we could move them all under some dir in items (maybe under relics?) in a folder called whistles, then update the server emote config to point to that folder. I could handle the latter part, if we could just agree on a folder and refactor everything in this PR that'd be pretty nice

**Comment by 0ffz** [comment]
Take a look at [this line](https://github.com/MineInAbyss/server-config/blob/master/servers/minecraft/plugins/BondrewdLikesHisEmotes/config.yml#L36) in emote config. Could you please do this for all the whistle emotes then open a PR on that branch? Add the new emotes as well. Once it's on the server it won't break existing emotes since this is entirely resourcepack dependant. We can then just copy the updated emotes json into here and everything will still work even for people on older resourcepack versions.

**Review by 0ffz — APPROVED** [review]
Merge in after server config is updated. Also for future reference, just try to split unrelated things up into more PRs, I'm guilty of not doing that more than I'd like to admit.

**Pull request merged**
