### PR TITLE
model fixes

### PR DESCRIPTION
**Pull request by xLightn1ng**
Fix:
netherite dagger
gate of babylon
New:
excalibur alter added

### CODE REVIEW

**Comment by Boy0000** [comment]
image
Do you wanna rescale it so you see the entire thing or? If you think that is fine then seems good.
Lowered netherite dagger as it feels weird having it so high up as one would simply be holding the end of it but

**Comment by xLightn1ng** [comment]
How big is that sword compared to the normal excalibur, if they are about the same size it should be good

**Comment by Boy0000** [comment]
image
this is what i mean in regards to the netherite dagger looking weird.

the sword is the same so iguess

**Comment by xLightn1ng** [comment]
Alright, it should be good then.

**Comment by Boy0000** [comment]
soo i should not lower the dagger to not look like the player is barely holding it?

**Comment by xLightn1ng** [comment]
No go ahead and move it down a bit, I agree with that change

**Comment by Boy0000** [comment]
image
also is this intentional for offhand?

**Comment by xLightn1ng** [comment]
I think its intentional, Luna made the model. I think it's a reverse grip.

**Comment by Boy0000** [comment]
hmm looks weird since it would be floating. unlike in main hand where there is a hand model. oh well guess fun easteregg

**Pull request merged**
